import { Clock3, Mail, MapPin, Phone } from 'lucide-react'
import ContactForm from '@/components/ContactForm'
import Container from '@/components/Container'
import FAQSection from '@/components/FAQSection'
import Seo from '@/components/Seo'
import { homeFaqs, organizationSchema, siteUrl } from '@/data/site'

const contactSchema = { ...organizationSchema, url: `${siteUrl}/contact`, contactPoint: { '@type': 'ContactPoint', contactType: 'sales and support', email: 'hello@flowpilot.example', telephone: '+1-415-555-0148', availableLanguage: 'English' } }

function ContactPage() { return <><Seo title="Contact" path="/contact" description="Talk to the FlowPilot team about AI workflow automation for your business." schema={contactSchema} /><main><section className="bg-slate-950 py-20 text-white sm:py-24"><Container><p className="text-sm font-bold uppercase tracking-widest text-indigo-300">Let’s talk</p><h1 className="mt-4 max-w-2xl text-4xl font-bold tracking-tight sm:text-5xl">Bring calm to your most complex work.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Tell us what your team is trying to move forward. We’ll show you what’s possible with FlowPilot.</p></Container></section><Container className="grid gap-12 py-20 lg:grid-cols-[.85fr_1.15fr] sm:py-28"><aside><h2 className="text-2xl font-bold tracking-tight text-slate-950">Contact FlowPilot</h2><p className="mt-4 leading-7 text-slate-600">Our team is here to help you build better workflows, from your first automation to enterprise-wide orchestration.</p><dl className="mt-8 space-y-6">{[[Mail, 'Email', 'hello@flowpilot.example', 'mailto:hello@flowpilot.example'], [Phone, 'Phone', '+1 (415) 555-0148', 'tel:+14155550148'], [MapPin, 'Office', '548 Market Street, San Francisco, CA', null], [Clock3, 'Hours', 'Monday–Friday, 9am–5pm PT', null]].map(([Icon, label, value, href]) => <div key={label} className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-indigo-50 text-indigo-600"><Icon className="size-5" aria-hidden="true" /></span><div><dt className="text-sm font-semibold text-slate-950">{label}</dt><dd className="mt-1 text-sm leading-6 text-slate-600">{href ? <a className="hover:text-indigo-600" href={href}>{value}</a> : value}</dd></div></div>)}</dl><div className="mt-10 overflow-hidden rounded-2xl border border-slate-200 bg-slate-100"><div className="grid h-52 place-items-center bg-[radial-gradient(circle_at_20%_30%,#c7d2fe_0,transparent_20%),radial-gradient(circle_at_70%_65%,#bae6fd_0,transparent_28%)]"><div className="rounded-full bg-indigo-600 p-3 text-white shadow-lg"><MapPin className="size-6" aria-hidden="true" /></div></div><p className="border-t border-slate-200 bg-white px-4 py-3 text-sm font-medium text-slate-700">FlowPilot HQ · San Francisco</p></div></aside><div><h2 className="text-2xl font-bold tracking-tight text-slate-950">Tell us about your workflow</h2><p className="mt-3 text-slate-600">We’ll connect you with the right specialist.</p><div className="mt-7"><ContactForm /></div></div></Container><section className="bg-slate-100 py-20 sm:py-28"><Container><FAQSection faqs={homeFaqs} title="Before we connect" description="A few common questions about getting started." /></Container></section></main></> }

export default ContactPage
