import { BarChart3, Bot, GitBranch, ShieldCheck, Sparkles, UsersRound } from 'lucide-react'
import CTASection from '@/components/CTASection'
import Container from '@/components/Container'
import FAQSection from '@/components/FAQSection'
import FeatureSection from '@/components/FeatureSection'
import Hero from '@/components/Hero'
import Seo from '@/components/Seo'
import TestimonialSection from '@/components/TestimonialSection'
import { homeFaqs, organizationSchema, testimonials } from '@/data/site'

const features = [{ icon: Bot, title: 'AI that takes action', description: 'Turn context from across your tools into useful next steps, summaries, and decisions.' }, { icon: GitBranch, title: 'Automation without friction', description: 'Design reliable workflows visually, then iterate as your business changes.' }, { icon: ShieldCheck, title: 'Governance built in', description: 'Keep every process observable with approvals, permissions, and audit trails.' }]

function HomePage() { return <><Seo title="FlowPilot" description="FlowPilot is the AI-powered workflow platform that helps growing businesses automate work with confidence." schema={organizationSchema} /><main><Hero /><Container className="py-20 sm:py-28"><FeatureSection eyebrow="Built for better operations" title="The operating system for work that matters" description="Connect people, systems, and AI in one calm, controllable workspace." features={features} /><section className="mt-28 grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">From signal to action</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Move every request forward—without chasing updates.</h2><p className="mt-5 text-lg leading-8 text-slate-600">FlowPilot spots the next best step, assigns the right owner, and keeps stakeholders in the loop automatically.</p><ul className="mt-8 space-y-5">{[{ icon: UsersRound, text: 'Give every team a shared source of truth.' }, { icon: Sparkles, text: 'Let AI handle the repetitive coordination.' }, { icon: BarChart3, text: 'See where work stalls before it becomes a problem.' }].map(({ icon: Icon, text }) => <li key={text} className="flex items-center gap-3 font-medium text-slate-800"><span className="grid size-10 place-items-center rounded-lg bg-indigo-50 text-indigo-600"><Icon className="size-5" aria-hidden="true" /></span>{text}</li>)}</ul></div><div className="rounded-3xl bg-gradient-to-br from-indigo-100 to-cyan-50 p-6 sm:p-10"><div className="rounded-2xl bg-white p-5 shadow-lg"><p className="text-sm font-bold text-slate-950">Weekly workflow health</p><div className="mt-6 flex h-36 items-end gap-3">{[45, 62, 54, 78, 70, 92, 88].map((height, index) => <div key={index} className="flex-1 rounded-t-md bg-indigo-500" style={{ height: `${height}%` }} />)}</div><div className="mt-4 flex justify-between text-xs text-slate-400"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></div></section></Container><section className="bg-slate-100 py-20 sm:py-28"><Container><TestimonialSection testimonials={testimonials} /></Container></section><Container className="py-20 sm:py-28"><FAQSection faqs={homeFaqs} /></Container></main><CTASection /></> }

export default HomePage
