import CTASection from '@/components/CTASection'
import Container from '@/components/Container'
import FAQSection from '@/components/FAQSection'
import PricingCard from '@/components/PricingCard'
import Seo from '@/components/Seo'
import { faqPageSchema, homeFaqs, pricingPlans, siteUrl } from '@/data/site'

const pricingSchema = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Product', name: 'FlowPilot', description: 'AI-powered workflow orchestration software for modern business teams.', url: `${siteUrl}/pricing`, offers: pricingPlans.filter(({ price }) => price !== 'Custom').map(({ name, price }) => ({ '@type': 'Offer', name, price: price.replace(/[^0-9]/g, ''), priceCurrency: 'USD', availability: 'https://schema.org/InStock' })) }, { '@type': 'FAQPage', mainEntity: faqPageSchema.mainEntity }] }

function PricingPage() { return <><Seo title="Pricing" path="/pricing" description="Explore simple, scalable FlowPilot plans for every stage of workflow automation." schema={pricingSchema} /><main><section className="bg-slate-950 py-20 text-center text-white sm:py-28"><Container><p className="text-sm font-bold uppercase tracking-widest text-indigo-300">Simple, scalable pricing</p><h1 className="mx-auto mt-4 max-w-3xl text-4xl font-bold tracking-tight sm:text-5xl">Automation that pays for itself.</h1><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-300">Choose the plan that fits today. Scale your operational advantage when you’re ready.</p></Container></section><Container className="py-20 sm:py-28"><div className="grid gap-6 lg:grid-cols-3">{pricingPlans.map((plan) => <PricingCard key={plan.name} {...plan} />)}</div><section className="mt-28 overflow-x-auto"><h2 className="text-center text-3xl font-bold tracking-tight text-slate-950">Compare plans at a glance</h2><table className="mt-10 w-full min-w-[620px] border-separate border-spacing-0 overflow-hidden rounded-2xl border border-slate-200 text-left text-sm"><thead className="bg-slate-50"><tr><th scope="col" className="p-4 font-semibold text-slate-950">Capability</th><th scope="col" className="p-4 font-semibold text-slate-950">Starter</th><th scope="col" className="p-4 font-semibold text-slate-950">Professional</th><th scope="col" className="p-4 font-semibold text-slate-950">Enterprise</th></tr></thead><tbody>{[['Active workflows', '5', 'Unlimited', 'Unlimited'], ['Connected apps', '3', '25', 'Unlimited'], ['Workflow analytics', '—', 'Included', 'Included'], ['Security controls', 'Standard', 'Advanced', 'Custom'], ['Support', 'Community', 'Priority', 'Dedicated']].map(([feature, ...values]) => <tr key={feature} className="border-t border-slate-200"><th scope="row" className="border-t border-slate-200 p-4 font-medium text-slate-800">{feature}</th>{values.map((value) => <td key={value} className="border-t border-slate-200 p-4 text-slate-600">{value}</td>)}</tr>)}</tbody></table></section><section className="mt-28"><FAQSection faqs={homeFaqs} title="Pricing questions" description="Get the details you need before choosing your plan." /></section></Container></main><CTASection title="Need a plan built around your business?" description="Our team can help shape the right FlowPilot rollout for your organization." /></> }

export default PricingPage
